stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: petclinic:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34266
  when:
    branch:
      include:
      - main
timeout: 60
notification: {}
